image: continuumio/anaconda:2018.12

before_script:
  - python --version
  - pip install requests faker voluptuous selenium nose configparser

test:
  script:
    - tags:demo
    - cd testsuites
    - python suite.py